spring:
 application:
  name: payment-api
 main:
   allow-bean-definition-overriding: true
server:
 port: ${PORT:8100} 
 
eureka:
 client: 
  service-url:
   default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
   #defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}